### ISSUE TITLE
Boost.Stacktrace libraries are not being installed by `b2 install`

### ISSUE THREAD

**Issue by Lastique** [boostorg/boost_install#55]
Running the following command line:

```
bjam -j 8 --prefix="$HOME/boost_install_root" toolset=gcc variant=release threading=multi debug-symbols=on runtime-link=shared numa=on link=static,shared --with-stacktrace install
```

does not result in Boost.Stacktrace libraries installed in `$HOME/boost_install_root`. The library is being successfully built, and its libraries are present in `$BOOST_ROOT/bin.v2`, but the only thing that is installed is CMake config files - no headers, no libraries.

This is a regression in 1.78, 1.77 worked fine. Boost.Stacktrace hasn't changed in this regard between releases, so my current suspects are Boost.Install or Boost.Build.

This is on Kubuntu 21.10.

Note that for other libraries, like Boost.Atomic for example, the above command works as intended.

**Comment by Lastique** [comment]
Sorry, this seems to be a duplicate of https://github.com/bfgroup/b2/issues/104.

**Comment by pdimov** [comment]
Looks like this also affects Fiber: https://github.com/boostorg/fiber/issues/290.
